[book]
title = "Rust By Example"
description = "Bản dịch tiếng Việt của Rust by Example"
author = "chinhnotional <eyescryptoinsights@gmail.com>"

[output.html.playpen]
editable = true
editor = "ace"

[output.html.fold]
enable = true

[output.html]
git-repository-url = "https://github.com/EyesCrypto-Insights/rust-by-example-vn"

[rust]
edition = "2021"